[2024-03-28T02:57:49.681+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:57:49.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T02:57:49.685+0000] {logging_mixin.py:188} INFO - [2024-03-28T02:57:49.685+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:57:49.695+0000] {logging_mixin.py:188} INFO - [2024-03-28T02:57:49.694+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-28T02:57:49.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:57:49.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.042 seconds
[2024-03-28T02:58:20.368+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:58:20.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T02:58:20.371+0000] {logging_mixin.py:188} INFO - [2024-03-28T02:58:20.371+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:58:20.377+0000] {logging_mixin.py:188} INFO - [2024-03-28T02:58:20.376+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-28T02:58:20.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:58:20.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.033 seconds
[2024-03-28T02:58:50.910+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:58:50.911+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T02:58:50.912+0000] {logging_mixin.py:188} INFO - [2024-03-28T02:58:50.912+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:58:50.919+0000] {logging_mixin.py:188} INFO - [2024-03-28T02:58:50.918+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-28T02:58:50.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:58:50.938+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.034 seconds
[2024-03-28T02:59:21.431+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:59:21.433+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T02:59:21.434+0000] {logging_mixin.py:188} INFO - [2024-03-28T02:59:21.433+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:59:21.440+0000] {logging_mixin.py:188} INFO - [2024-03-28T02:59:21.439+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-28T02:59:21.440+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:59:21.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.032 seconds
[2024-03-28T02:59:52.050+0000] {processor.py:161} INFO - Started process (PID=333) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:59:52.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T02:59:52.053+0000] {logging_mixin.py:188} INFO - [2024-03-28T02:59:52.053+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:59:52.061+0000] {logging_mixin.py:188} INFO - [2024-03-28T02:59:52.059+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-28T02:59:52.061+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T02:59:52.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.034 seconds
[2024-03-28T03:00:22.726+0000] {processor.py:161} INFO - Started process (PID=374) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:00:22.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:00:22.730+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:00:22.729+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:00:22.737+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:00:22.736+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-28T03:00:22.738+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:00:22.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.037 seconds
[2024-03-28T03:00:53.426+0000] {processor.py:161} INFO - Started process (PID=415) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:00:53.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:00:53.429+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:00:53.429+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:00:53.436+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:00:53.435+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-28T03:00:53.436+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:00:53.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.032 seconds
[2024-03-28T03:01:24.014+0000] {processor.py:161} INFO - Started process (PID=456) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:01:24.016+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:01:24.020+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:01:24.020+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:01:24.024+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:01:24.024+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-28T03:01:24.025+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:01:24.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.030 seconds
[2024-03-28T03:01:54.739+0000] {processor.py:161} INFO - Started process (PID=497) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:01:54.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:01:54.742+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:01:54.741+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:01:54.747+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:01:54.746+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-28T03:01:54.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:01:54.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.031 seconds
[2024-03-28T03:02:25.369+0000] {processor.py:161} INFO - Started process (PID=543) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:02:25.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:02:25.372+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:02:25.371+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:02:25.378+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:02:25.377+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-28T03:02:25.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:02:25.395+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.032 seconds
[2024-03-28T03:02:55.966+0000] {processor.py:161} INFO - Started process (PID=584) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:02:55.967+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:02:55.969+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:02:55.968+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:02:55.976+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:02:55.974+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 3, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-28T03:02:55.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:02:55.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.034 seconds
[2024-03-28T03:03:02.227+0000] {processor.py:161} INFO - Started process (PID=614) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:03:02.229+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:03:02.230+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:03:02.230+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:03:02.478+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:03:02.530+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:03:02.529+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:dag_with_python_dependencies_v01
[2024-03-28T03:03:02.534+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:03:02.534+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:dag_with_python_dependencies_v01
[2024-03-28T03:03:02.537+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:03:02.537+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:dag_with_python_dependencies_v01
[2024-03-28T03:03:02.538+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:03:02.537+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:03:02.543+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:03:02.543+0000] {dag.py:3069} INFO - Creating ORM DAG for dag_with_python_dependencies_v01
[2024-03-28T03:03:02.548+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:03:02.548+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v01 to 2024-03-25 00:00:00+00:00, run_after=2024-03-26 00:00:00+00:00
[2024-03-28T03:03:02.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.345 seconds
[2024-03-28T03:03:32.850+0000] {processor.py:161} INFO - Started process (PID=665) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:03:32.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:03:32.852+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:03:32.852+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:03:33.027+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:03:33.040+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:03:33.040+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:03:33.051+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:03:33.050+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v01 to 2024-03-25 00:00:00+00:00, run_after=2024-03-26 00:00:00+00:00
[2024-03-28T03:03:33.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.213 seconds
[2024-03-28T03:04:03.560+0000] {processor.py:161} INFO - Started process (PID=742) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:04:03.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:04:03.563+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:04:03.563+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:04:03.763+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:04:03.779+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:04:03.778+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:04:03.792+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:04:03.792+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v01 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:04:03.803+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.248 seconds
[2024-03-28T03:04:34.174+0000] {processor.py:161} INFO - Started process (PID=790) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:04:34.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:04:34.177+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:04:34.176+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:04:34.408+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:04:34.422+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:04:34.422+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:04:34.434+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:04:34.434+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v01 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:04:34.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.274 seconds
[2024-03-28T03:05:04.852+0000] {processor.py:161} INFO - Started process (PID=838) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:05:04.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:05:04.855+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:05:04.855+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:05:05.041+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:05:05.055+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:05:05.055+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:05:05.065+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:05:05.065+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v01 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:05:05.073+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.226 seconds
[2024-03-28T03:05:35.422+0000] {processor.py:161} INFO - Started process (PID=886) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:05:35.423+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:05:35.424+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:05:35.424+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:05:35.644+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:05:35.660+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:05:35.660+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:05:35.671+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:05:35.671+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v01 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:05:35.680+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.262 seconds
[2024-03-28T03:06:06.045+0000] {processor.py:161} INFO - Started process (PID=934) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:06:06.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:06:06.048+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:06:06.047+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:06:06.236+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:06:06.250+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:06:06.250+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:06:06.262+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:06:06.262+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v01 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:06:06.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.234 seconds
[2024-03-28T03:06:36.627+0000] {processor.py:161} INFO - Started process (PID=982) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:06:36.629+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:06:36.630+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:06:36.630+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:06:36.812+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:06:36.826+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:06:36.826+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:06:36.839+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:06:36.839+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v01 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:06:36.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.227 seconds
[2024-03-28T03:07:07.163+0000] {processor.py:161} INFO - Started process (PID=1030) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:07:07.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:07:07.165+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:07:07.164+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:07:07.387+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:07:07.402+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:07:07.402+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:07:07.415+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:07:07.415+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v01 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:07:07.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.265 seconds
[2024-03-28T03:07:37.720+0000] {processor.py:161} INFO - Started process (PID=1078) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:07:37.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:07:37.723+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:07:37.722+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:07:37.902+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:07:37.916+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:07:37.916+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:07:37.927+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:07:37.927+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v01 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:07:37.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.219 seconds
[2024-03-28T03:08:08.340+0000] {processor.py:161} INFO - Started process (PID=1126) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:08:08.341+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:08:08.342+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:08:08.341+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:08:08.521+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:08:08.535+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:08:08.535+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:08:08.545+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:08:08.545+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v01 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:08:08.553+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.216 seconds
[2024-03-28T03:08:38.900+0000] {processor.py:161} INFO - Started process (PID=1174) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:08:38.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:08:38.903+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:08:38.902+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:08:39.099+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:08:39.111+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:08:39.111+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:08:39.122+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:08:39.122+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v01 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:08:39.130+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.235 seconds
[2024-03-28T03:09:09.444+0000] {processor.py:161} INFO - Started process (PID=1222) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:09:09.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:09:09.447+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:09:09.447+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:09:09.654+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v01' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:09:09.670+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:09:09.670+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:09:09.683+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:09:09.682+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v01 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:09:09.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.256 seconds
[2024-03-28T03:09:27.725+0000] {processor.py:161} INFO - Started process (PID=1245) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:09:27.727+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:09:27.729+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:09:27.728+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:09:27.909+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:09:27.908+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:09:27.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:09:27.921+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.200 seconds
[2024-03-28T03:09:58.382+0000] {processor.py:161} INFO - Started process (PID=1293) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:09:58.384+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:09:58.385+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:09:58.385+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:09:58.568+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:09:58.568+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:09:58.569+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:09:58.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.202 seconds
[2024-03-28T03:10:29.009+0000] {processor.py:161} INFO - Started process (PID=1340) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:10:29.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:10:29.011+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:10:29.011+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:10:29.195+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:10:29.194+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:10:29.195+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:10:29.207+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.201 seconds
[2024-03-28T03:10:59.734+0000] {processor.py:161} INFO - Started process (PID=1388) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:10:59.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:10:59.735+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:10:59.735+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:10:59.925+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:10:59.924+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:10:59.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:10:59.935+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.205 seconds
[2024-03-28T03:11:14.136+0000] {processor.py:161} INFO - Started process (PID=1425) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:11:14.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:11:14.138+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:11:14.138+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:11:14.325+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:11:14.324+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:11:14.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:11:14.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.203 seconds
[2024-03-28T03:11:23.259+0000] {processor.py:161} INFO - Started process (PID=1443) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:11:23.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:11:23.262+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:11:23.261+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:11:23.447+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:11:23.447+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:11:23.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:11:23.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.205 seconds
[2024-03-28T03:11:54.102+0000] {processor.py:161} INFO - Started process (PID=1491) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:11:54.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:11:54.104+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:11:54.103+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:11:54.314+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:11:54.313+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:11:54.315+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:11:54.327+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.228 seconds
[2024-03-28T03:12:24.732+0000] {processor.py:161} INFO - Started process (PID=1539) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:12:24.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:12:24.734+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:12:24.734+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:12:24.925+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:12:24.924+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:12:24.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:12:24.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.207 seconds
[2024-03-28T03:12:55.390+0000] {processor.py:161} INFO - Started process (PID=1587) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:12:55.392+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:12:55.393+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:12:55.393+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:12:55.609+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:12:55.608+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:12:55.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:12:55.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.237 seconds
[2024-03-28T03:13:26.049+0000] {processor.py:161} INFO - Started process (PID=1635) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:13:26.050+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:13:26.052+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:13:26.051+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:13:26.244+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:13:26.243+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:13:26.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:13:26.256+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.211 seconds
[2024-03-28T03:13:56.669+0000] {processor.py:161} INFO - Started process (PID=1683) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:13:56.670+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:13:56.671+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:13:56.671+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:13:56.853+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:13:56.852+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:13:56.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:13:56.866+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.201 seconds
[2024-03-28T03:14:27.347+0000] {processor.py:161} INFO - Started process (PID=1731) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:14:27.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:14:27.350+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:14:27.349+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:14:27.532+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:14:27.532+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:14:27.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:14:27.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.200 seconds
[2024-03-28T03:14:57.967+0000] {processor.py:161} INFO - Started process (PID=1779) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:14:57.968+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:14:57.969+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:14:57.969+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:14:58.147+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:14:58.147+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:14:58.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:14:58.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.195 seconds
[2024-03-28T03:15:28.619+0000] {processor.py:161} INFO - Started process (PID=1827) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:15:28.620+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:15:28.620+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:15:28.620+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:15:28.801+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:15:28.800+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:15:28.801+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:15:28.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.195 seconds
[2024-03-28T03:15:59.260+0000] {processor.py:161} INFO - Started process (PID=1875) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:15:59.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:15:59.262+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:15:59.261+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:15:59.425+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:15:59.424+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:15:59.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:15:59.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.178 seconds
[2024-03-28T03:16:29.951+0000] {processor.py:161} INFO - Started process (PID=1923) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:16:29.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:16:29.954+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:16:29.954+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:16:30.135+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:16:30.134+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:16:30.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:16:30.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.200 seconds
[2024-03-28T03:17:00.538+0000] {processor.py:161} INFO - Started process (PID=1971) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:17:00.539+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:17:00.541+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:17:00.540+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:17:00.739+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:17:00.738+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:17:00.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:17:00.749+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.216 seconds
[2024-03-28T03:17:31.193+0000] {processor.py:161} INFO - Started process (PID=2019) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:17:31.194+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:17:31.196+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:17:31.195+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:17:31.375+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:17:31.374+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:17:31.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:17:31.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.198 seconds
[2024-03-28T03:18:01.876+0000] {processor.py:161} INFO - Started process (PID=2067) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:18:01.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:18:01.880+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:18:01.880+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:18:02.054+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:18:02.053+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:18:02.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:18:02.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.193 seconds
[2024-03-28T03:18:32.515+0000] {processor.py:161} INFO - Started process (PID=2115) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:18:32.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:18:32.518+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:18:32.518+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:18:32.698+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:18:32.697+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:18:32.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:18:32.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.199 seconds
[2024-03-28T03:19:03.212+0000] {processor.py:161} INFO - Started process (PID=2163) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:19:03.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:19:03.215+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:19:03.214+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:19:03.396+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:19:03.395+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:19:03.396+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:19:03.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.201 seconds
[2024-03-28T03:19:33.783+0000] {processor.py:161} INFO - Started process (PID=2211) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:19:33.784+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:19:33.785+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:19:33.785+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:19:33.960+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:19:33.960+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:19:33.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:19:33.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.191 seconds
[2024-03-28T03:20:04.434+0000] {processor.py:161} INFO - Started process (PID=2259) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:20:04.435+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:20:04.436+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:20:04.436+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:20:04.627+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:20:04.626+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:20:04.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:20:04.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.208 seconds
[2024-03-28T03:20:35.017+0000] {processor.py:161} INFO - Started process (PID=2307) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:20:35.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:20:35.020+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:20:35.019+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:20:35.204+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:20:35.203+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:20:35.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:20:35.216+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.205 seconds
[2024-03-28T03:21:05.568+0000] {processor.py:161} INFO - Started process (PID=2355) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:21:05.569+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:21:05.571+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:21:05.570+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:21:05.777+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:21:05.775+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:21:05.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:21:05.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.231 seconds
[2024-03-28T03:21:36.168+0000] {processor.py:161} INFO - Started process (PID=2403) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:21:36.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:21:36.172+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:21:36.171+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:21:36.350+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:21:36.350+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:21:36.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:21:36.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.198 seconds
[2024-03-28T03:22:06.741+0000] {processor.py:161} INFO - Started process (PID=2452) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:22:06.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:22:06.742+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:22:06.742+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:22:06.914+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:22:06.913+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:22:06.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:22:06.924+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.186 seconds
[2024-03-28T03:22:37.400+0000] {processor.py:161} INFO - Started process (PID=2501) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:22:37.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:22:37.403+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:22:37.403+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:22:37.595+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:22:37.594+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:22:37.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:22:37.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.210 seconds
[2024-03-28T03:23:08.034+0000] {processor.py:161} INFO - Started process (PID=2549) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:23:08.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:23:08.036+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:23:08.036+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:23:08.235+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:23:08.235+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:23:08.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:23:08.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.219 seconds
[2024-03-28T03:23:38.653+0000] {processor.py:161} INFO - Started process (PID=2597) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:23:38.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:23:38.656+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:23:38.655+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:23:38.830+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:23:38.830+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:23:38.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:23:38.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.193 seconds
[2024-03-28T03:24:09.285+0000] {processor.py:161} INFO - Started process (PID=2645) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:24:09.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:24:09.287+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:24:09.287+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:24:09.508+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:24:09.507+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:24:09.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:24:09.521+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.239 seconds
[2024-03-28T03:24:39.914+0000] {processor.py:161} INFO - Started process (PID=2693) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:24:39.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:24:39.917+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:24:39.916+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:24:40.110+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:24:40.109+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:24:40.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:24:40.123+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.213 seconds
[2024-03-28T03:25:10.567+0000] {processor.py:161} INFO - Started process (PID=2741) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:25:10.569+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:25:10.570+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:25:10.570+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:25:10.777+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:25:10.776+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:25:10.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:25:10.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.227 seconds
[2024-03-28T03:25:41.301+0000] {processor.py:161} INFO - Started process (PID=2789) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:25:41.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:25:41.303+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:25:41.303+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:25:41.522+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:25:41.522+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:25:41.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:25:41.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.238 seconds
[2024-03-28T03:26:11.983+0000] {processor.py:161} INFO - Started process (PID=2837) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:26:11.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:26:11.986+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:26:11.985+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:26:12.157+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:26:12.156+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:26:12.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:26:12.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.190 seconds
[2024-03-28T03:26:42.599+0000] {processor.py:161} INFO - Started process (PID=2885) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:26:42.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:26:42.600+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:26:42.600+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:26:42.817+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:26:42.817+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:26:42.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:26:42.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.235 seconds
[2024-03-28T03:27:13.284+0000] {processor.py:161} INFO - Started process (PID=2933) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:27:13.285+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:27:13.287+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:27:13.286+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:27:13.472+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:27:13.472+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:27:13.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:27:13.484+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.205 seconds
[2024-03-28T03:27:43.836+0000] {processor.py:161} INFO - Started process (PID=2981) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:27:43.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:27:43.840+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:27:43.839+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:27:44.036+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:27:44.035+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:27:44.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:27:44.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.215 seconds
[2024-03-28T03:28:14.477+0000] {processor.py:161} INFO - Started process (PID=3029) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:28:14.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:28:14.481+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:28:14.480+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:28:14.692+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:28:14.691+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:28:14.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:28:14.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.234 seconds
[2024-03-28T03:28:45.072+0000] {processor.py:161} INFO - Started process (PID=3077) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:28:45.073+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:28:45.075+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:28:45.074+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:28:45.255+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:28:45.254+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:28:45.255+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:28:45.265+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.199 seconds
[2024-03-28T03:29:20.169+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:29:20.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:29:20.175+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:29:20.175+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:29:20.426+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:29:20.425+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:29:20.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:29:20.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.272 seconds
[2024-03-28T03:29:51.038+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:29:51.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:29:51.041+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:29:51.041+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:29:51.258+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:29:51.257+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:29:51.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:29:51.268+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.235 seconds
[2024-03-28T03:30:21.731+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:30:21.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:30:21.734+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:30:21.733+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:30:21.937+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:30:21.937+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:30:21.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:30:21.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.224 seconds
[2024-03-28T03:30:52.492+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:30:52.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:30:52.494+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:30:52.494+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:30:52.732+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:30:52.731+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:30:52.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:30:52.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.255 seconds
[2024-03-28T03:31:23.197+0000] {processor.py:161} INFO - Started process (PID=361) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:31:23.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:31:23.199+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:31:23.199+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:31:23.421+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:31:23.421+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:31:23.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:31:23.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.241 seconds
[2024-03-28T03:31:53.938+0000] {processor.py:161} INFO - Started process (PID=409) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:31:53.939+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:31:53.941+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:31:53.940+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:31:54.156+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:31:54.155+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:31:54.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:31:54.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.234 seconds
[2024-03-28T03:32:24.711+0000] {processor.py:161} INFO - Started process (PID=457) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:32:24.712+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:32:24.714+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:32:24.713+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:32:24.926+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:32:24.926+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:32:24.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:32:24.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.232 seconds
[2024-03-28T03:32:55.404+0000] {processor.py:161} INFO - Started process (PID=505) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:32:55.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:32:55.407+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:32:55.406+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:32:55.608+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:32:55.608+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:32:55.609+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:32:55.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.221 seconds
[2024-03-28T03:33:26.137+0000] {processor.py:161} INFO - Started process (PID=553) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:33:26.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:33:26.141+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:33:26.140+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:33:26.368+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:33:26.367+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:33:26.369+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:33:26.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.245 seconds
[2024-03-28T03:33:56.865+0000] {processor.py:161} INFO - Started process (PID=601) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:33:56.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:33:56.867+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:33:56.867+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:33:57.059+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:33:57.059+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:33:57.060+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:33:57.070+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.211 seconds
[2024-03-28T03:34:27.690+0000] {processor.py:161} INFO - Started process (PID=649) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:34:27.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:34:27.693+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:34:27.693+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:34:27.890+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:34:27.890+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:34:27.891+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:34:27.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.217 seconds
[2024-03-28T03:34:58.415+0000] {processor.py:161} INFO - Started process (PID=697) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:34:58.416+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:34:58.417+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:34:58.416+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:34:58.613+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:34:58.612+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-03-28T03:34:58.614+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:34:58.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.214 seconds
[2024-03-28T03:35:29.116+0000] {processor.py:161} INFO - Started process (PID=776) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:35:29.117+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:35:29.119+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:35:29.118+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:35:29.416+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v02' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:35:29.630+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:35:29.629+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:dag_with_python_dependencies_v02
[2024-03-28T03:35:29.634+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:35:29.634+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:dag_with_python_dependencies_v02
[2024-03-28T03:35:29.636+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:35:29.636+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:dag_with_python_dependencies_v02
[2024-03-28T03:35:29.644+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:35:29.643+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:35:29.654+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:35:29.654+0000] {dag.py:3069} INFO - Creating ORM DAG for dag_with_python_dependencies_v02
[2024-03-28T03:35:29.659+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:35:29.659+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v02 to 2024-03-25 00:00:00+00:00, run_after=2024-03-26 00:00:00+00:00
[2024-03-28T03:35:29.669+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.560 seconds
[2024-03-28T03:35:59.986+0000] {processor.py:161} INFO - Started process (PID=824) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:35:59.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:35:59.988+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:35:59.987+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:36:00.246+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v02' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:36:00.260+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:36:00.260+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:36:00.374+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:36:00.374+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v02 to 2024-03-25 00:00:00+00:00, run_after=2024-03-26 00:00:00+00:00
[2024-03-28T03:36:00.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.399 seconds
[2024-03-28T03:36:16.748+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:36:16.749+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:36:16.750+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:36:16.749+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:36:17.003+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v02' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:36:17.024+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:36:17.024+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:36:17.037+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:36:17.037+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v02 to 2024-03-25 00:00:00+00:00, run_after=2024-03-26 00:00:00+00:00
[2024-03-28T03:36:17.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.304 seconds
[2024-03-28T03:36:47.505+0000] {processor.py:161} INFO - Started process (PID=270) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:36:47.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:36:47.508+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:36:47.507+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:36:47.742+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v02' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:36:47.756+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:36:47.756+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:36:47.768+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:36:47.768+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v02 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:36:47.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.278 seconds
[2024-03-28T03:37:18.253+0000] {processor.py:161} INFO - Started process (PID=318) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:37:18.255+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:37:18.257+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:37:18.257+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:37:18.512+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v02' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:37:18.527+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:37:18.526+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:37:18.539+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:37:18.538+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v02 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:37:18.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.410 seconds
[2024-03-28T03:37:49.047+0000] {processor.py:161} INFO - Started process (PID=366) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:37:49.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:37:49.050+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:37:49.050+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:37:49.302+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v02' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:37:49.316+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:37:49.316+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:37:49.449+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:37:49.449+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v02 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:37:49.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.418 seconds
[2024-03-28T03:38:19.882+0000] {processor.py:161} INFO - Started process (PID=414) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:38:19.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:38:19.885+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:38:19.885+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:38:20.164+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v02' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:38:20.179+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:38:20.179+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:38:20.194+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:38:20.193+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v02 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:38:20.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.325 seconds
[2024-03-28T03:38:50.726+0000] {processor.py:161} INFO - Started process (PID=462) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:38:50.727+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:38:50.728+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:38:50.728+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:38:50.944+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v02' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:38:50.957+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:38:50.957+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:38:50.968+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:38:50.968+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v02 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:38:50.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.257 seconds
[2024-03-28T03:39:21.531+0000] {processor.py:161} INFO - Started process (PID=510) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:39:21.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2024-03-28T03:39:21.534+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:39:21.534+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:39:21.822+0000] {processor.py:840} INFO - DAG(s) 'dag_with_python_dependencies_v02' retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2024-03-28T03:39:21.839+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:39:21.838+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-28T03:39:21.851+0000] {logging_mixin.py:188} INFO - [2024-03-28T03:39:21.851+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_with_python_dependencies_v02 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-28T03:39:21.861+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.334 seconds
